#Spring-boot main properties
spring:
  profiles:
    default: none
    active: none
  application:
    name: Danager

server:
  port: 8080

danager:
  test: "hello"
  commands:
    prefix: "!"


discord:
  token: "MzQxMTgwNTQ4MDQxMTQ2MzY5.XOhbjQ.DtYdNed8l9gAwz7uzCwL-PbUA2E"

